<?php

namespace Database\Seeders;

use App\Models\JobTitle;
use Illuminate\Database\Seeder;

class JobTitleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobTitles = [
            'DRIVER',
            'GADGET SPECIALIST LEADER (WJ1)',
            'MT WAREHOUSE STAFF',
            'MT FINANCE STAFF E-COMMERCE',
            'AREA SALES COORDINATOR REALME',
            'ADMIN PROGRAM',
            'SALES ASSOCIATE',
            'STAFF ADMIN LOGISTIK',
            'MT SALES TECNO',
            'STAFF WAREHOUSE',
            'OFFICE BOY',
            'STAFF AR',
            'CUSTOMER SERVICE',
            'GADGET SPECIALIST (WJ2)',
            'STAFF INVENTORY CONTROL',
            'ADMINISTRATOR SP',
            'STAFF SPV',
            'TEAM LEADER PROFIL',
            'FINANCE TAX STAFF',
            'GENERAL AFFAIR STAFF',
            'INTERNAL AUDIT STAFF',
            'HRD RECRUITMENT',
            'DIGITAL MARKETING SPECIALIST',
            'SPV PROFIL CS',
            'CHIEF OPERATING OFFICER',
            'SPV AUDIT IT & SISTEM OPERASIONAL',
            'FINANCE AR STAFF',
            'FINANCE SPV',
            'TAX SPECIALIST LEADER',
            'LOGISTIC STAFF',
            'HRD TRAINING & DEVELOPMENT',
            'WAREHOUSE STAFF',
            'PROGRAMMER',
            'GA MAINTENANCE SPECIALIST',
            'SPV FINANCE',
            'IT SUPPORT',
            'HEAD OF RETAIL SALES',
            'TAX SPECIALIST',
            'EXECUTIVE SECRETARY',
            'PROMOTER TECNO',
            'HEAD OF LOGISTICS WAREHOUSE',
            'AREA SALES MANAGER REALME',
            'CHIEF FINANCIAL OFFICER',
            'SALES PROMOTER TECNO',
            'LEADER PROFIL CS',
            'HRD STAFF',
            'ACCOUNTING SPECIALIST',
            'LEADER E-COMMERCE',
            'CHIEF EXECUTIVE OFFICER',
            'FINANCE CONTROLLER SPV',
            'HEAD OF HUMAN CAPITAL',
            'SPV TAX',
            'CHIEF MARKETING OFFICER',
            'LEADER GADGET SPECIALIST',
            'STAFF ACCOUNTING',
            'LEADER SERVICE CENTER',
            'RETAIL SALES LEADER',
            'SALES FORCE INIFINIX',
            'SPV AUDIT INTERNAL',
            'MT GENERAL AFFAIR',
            'LEADER INVENTORY CONTROL',
            'SERVICE CENTER SPECIALIST',
            'LEADER PRODUCER',
            'LEADER HRD RECRUITMENT',
            'STAFF LOGISTIK',
            'SPV ACCOUNTING',
            'STAFF TAX',
            'STAFF AUDIT INTERNAL',
            'GENERAL MANAGER',
            'AREA SALES COORDINATOR INIFINIX',
            'HEAD OF DIGITAL MARKETING',
            'INTERNAL AUDIT SPV',
            'STAFF IT SUPPORT',
            'SPV LOGISTIK & WAREHOUSE',
            'HEAD OF FINANCE & ACCOUNTING',
            'HEAD OF IT',
            'OPERATIONAL DIRECTOR',
            'AREA SALES MANAGER TECNO',
            'LEADER CREATIVE',
            'LEADER GRAPHIC DESIGNER',
            'HEAD OF MERCHANDISING',
            'FINANCE & ACCOUNTING DIRECTOR',
            'LEADER DIGITAL MARKETING',
            'LEADER AUDIT OPERASIONAL',
            'LEADER CONTENT CREATOR',
            'LEADER COPYWRITER',
            'LEADER VIDEOGRAPHER',
            'LEADER SOCIAL MEDIA SPECIALIST',
            'LEADER SEO SPECIALIST',
            'LEADER DATA ANALYST',
            'LEADER PROJECT MANAGER',
            'LEADER BUSINESS DEVELOPMENT',
            'LEADER LEGAL',
            'LEADER COMPLIANCE',
            'LEADER PROCUREMENT',
            'LEADER FACILITY MANAGEMENT',
            'LEADER SECURITY',
            'LEADER HSE',
            'LEADER QUALITY CONTROL',
            'LEADER ASSET MANAGEMENT',
            'HEAD OF GENERAL AFFAIR',
            'HEAD OF LEGAL & COMPLIANCE',
            'HEAD OF PROCUREMENT',
            'HEAD OF INTERNAL AUDIT',
            'HEAD OF BUSINESS DEVELOPMENT',
            'HEAD OF PROJECT MANAGEMENT',
            'HEAD OF DATA & ANALYTICS',
            'HEAD OF CORPORATE COMMUNICATIONS',
            'HEAD OF CUSTOMER EXPERIENCE',
            'HEAD OF SUPPLY CHAIN',
            'DIRECTOR OF HUMAN RESOURCES',
            'DIRECTOR OF LOGISTICS',
            'DIRECTOR OF BUSINESS DEVELOPMENT',
            'COMMERCIAL DIRECTOR',
            'MANAGING DIRECTOR',
            'DEPUTY CEO',
            'VICE PRESIDENT OF OPERATIONS',
            'VICE PRESIDENT OF FINANCE',
            'VICE PRESIDENT OF TECHNOLOGY',
            'VICE PRESIDENT OF MARKETING',
            'VICE PRESIDENT OF SALES',
            'VICE PRESIDENT OF HUMAN RESOURCES',
            'EXECUTIVE VICE PRESIDENT',
            'SENIOR VICE PRESIDENT',
            'CHIEF INFORMATION OFFICER',
            'CHIEF TECHNOLOGY OFFICER',
            'CHIEF COMPLIANCE OFFICER',
            'CHIEF RISK OFFICER',
            'CHIEF REVENUE OFFICER',
            'CHIEF STRATEGY OFFICER',
            'CHIEF SUSTAINABILITY OFFICER',
            'CHIEF COMMERCIAL OFFICER',
            'CHIEF DATA OFFICER',
            'CHIEF SECURITY OFFICER',
            'BOARD MEMBER',
            'COMMISSIONER',
            'INDEPENDENT COMMISSIONER',
            'PRESIDENT COMMISSIONER',
            'ADVISOR',
            'SENIOR ADVISOR',
            'CONSULTANT',
            'EXPERT STAFF',
            'SPECIAL ASSISTANT TO CEO',
            'INTERNAL AUDITOR SENIOR',
            'ACCOUNTING MANAGER',
            'FINANCE MANAGER',
            'TAX MANAGER',
            'LOGISTICS MANAGER',
            'WAREHOUSE MANAGER',
            'PURCHASING MANAGER',
            'GA MANAGER',
            'LEGAL MANAGER',
            'IT MANAGER',
            'MARKETING MANAGER',
            'SALES MANAGER',
            'HR MANAGER',
            'OPERATIONS MANAGER',
            'REGIONAL SALES MANAGER',
            'NATIONAL SALES MANAGER',
            'BRAND MANAGER',
            'PRODUCT MANAGER',
            'PROJECT MANAGER',
            'STORE MANAGER',
            'BRANCH MANAGER',
            'AREA MANAGER',
            'GENERAL MANAGER OPERATIONS',
            'GENERAL MANAGER FINANCE',
            'GENERAL MANAGER HR',
            'GENERAL MANAGER MARKETING',
            'GENERAL MANAGER SALES',
            'GENERAL MANAGER IT',
            'SENIOR MANAGER',
            'ASSOCIATE DIRECTOR',
            'ASSISTANT MANAGER',
            'Asst. Sales Manager',
            'LEADER WAREHOUSE DAN LOGISTIK',
            'RETAIL STORE MANAGER',
            'FINANCE ACCOUNTING TAX MANAGER',
        ];

        foreach ($jobTitles as $title) {
            JobTitle::firstOrCreate(['title' => $title]);
        }
    }
}
