<?php

namespace Database\Factories;

use App\Enums\RequestStatus;
use App\Models\AssetRequest;
use App\Models\AssetRequestApproval;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<AssetRequestApproval>
 */
class AssetRequestApprovalFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<AssetRequestApproval>
     */
    protected $model = AssetRequestApproval::class;

    /**
     * Define the model's default state.
     *
     * `public_token` is auto-generated by the model's creating hook, so it is
     * omitted from the factory definition.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'asset_request_id' => AssetRequest::inRandomOrder()->first()->id ?? AssetRequest::factory(),
            'user_id' => User::inRandomOrder()->first()->id ?? User::factory(),
            'level' => fake()->numberBetween(1, 5),
            'status' => RequestStatus::Pending,
            'notes' => null,
            'decided_by_user_id' => null,
            'decided_at' => null,
        ];
    }
}
