<?php

namespace Database\Factories;

use App\Enums\AssetRequestType;
use App\Enums\RequestStatus;
use App\Models\AssetLocation;
use App\Models\AssetRequest;
use App\Models\Division;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<AssetRequest>
 */
class AssetRequestFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<AssetRequest>
     */
    protected $model = AssetRequest::class;

    /**
     * Define the model's default state.
     *
     * `reference_number` and `public_token` are auto-generated by the model's
     * creating hook, so they are omitted from the factory definition.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'type' => AssetRequestType::Pengadaan,
            'user_id' => User::inRandomOrder()->first()->id ?? User::factory(),
            'division_id' => Division::inRandomOrder()->first()->id ?? null,
            'asset_location_id' => AssetLocation::inRandomOrder()->first()->id ?? null,
            'asset_id' => null,
            'item_name' => fake()->optional()->words(2, true),
            'qty' => fake()->optional()->numberBetween(1, 10),
            'description' => fake()->optional()->sentence(),
            'attachment' => null,
            'status' => RequestStatus::Pending,
            'notes' => null,
            'current_level' => 1,
            'fulfilled_at' => null,
            'fulfilled_by_user_id' => null,
            'asset_transfer_id' => null,
        ];
    }
}
