<?php

namespace Database\Factories;

use App\Models\BusinessEntity;
use App\Models\Task;
use App\Models\Vendor;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Task>
 */
class TaskFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<Task>
     */
    protected $model = Task::class;

    /**
     * Define the model's default state.
     *
     * `code` is auto-generated by the model's creating hook, so it is omitted
     * from the factory definition.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'business_entity_id' => BusinessEntity::inRandomOrder()->first()->id ?? BusinessEntity::factory(),
            'work_timestamp' => fake()->dateTimeThisYear(),
            'name' => fake()->sentence(3),
            'description' => fake()->paragraph(),
            'vendor_id' => Vendor::inRandomOrder()->first()->id ?? Vendor::factory(),
            'cost' => fake()->numberBetween(1000, 1000000),
            'location' => fake()->city(),
            'status' => fake()->randomElement(['open', 'in_progress', 'completed']),
            'attachment' => null,
            'document_upload' => null,
        ];
    }
}
